# Generated by Django 3.2 on 2021-05-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_habilidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='jobs',
            new_name='job',
        ),
    ]
